/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d/TheGreatestSaveOfAllTime.gltf -t -r public 
*/
'use client'
import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Player: THREE.SkinnedMesh
    Shirt: THREE.SkinnedMesh
    Shoes: THREE.SkinnedMesh
    Shorts: THREE.SkinnedMesh
    Socks: THREE.SkinnedMesh
    Gloves001: THREE.SkinnedMesh
    Player001: THREE.SkinnedMesh
    Shirt001: THREE.SkinnedMesh
    Shoes001: THREE.SkinnedMesh
    Shorts001: THREE.SkinnedMesh
    Socks001: THREE.SkinnedMesh
    Mesh033: THREE.Mesh
    Mesh033_1: THREE.Mesh
    Mesh590: THREE.Mesh
    Mesh590_1: THREE.Mesh
    Pitch_Mark: THREE.Mesh
    Net: THREE.Mesh
    Grass: THREE.Mesh
    Bone: THREE.Bone
    Bone_1: THREE.Bone
  }
  materials: {
    Kolo: THREE.MeshStandardMaterial
    France: THREE.MeshStandardMaterial
    ['Kolo Boots']: THREE.MeshStandardMaterial
    Gloves: THREE.MeshStandardMaterial
    Dibu: THREE.MeshStandardMaterial
    Argentina: THREE.MeshStandardMaterial
    Boots: THREE.MeshStandardMaterial
    ['03 - Defaultdf']: THREE.MeshStandardMaterial
    ['03 - Defausdltdxc']: THREE.MeshStandardMaterial
    Bar: THREE.MeshStandardMaterial
    Net: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
  }
}

export default function Model() {
  const { scene } = useGLTF('/3d/TheGreatestSaveOfAllTime.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  return (
    <group dispose={null}>
      <group position={[3.422, 0, 0.272]} rotation={[0, -1.496, 0]} scale={[0.27, 0.277, 0.27]}>
        <primitive object={nodes.Bone} />
        <skinnedMesh castShadow receiveShadow geometry={nodes.Player.geometry} material={materials.Kolo} skeleton={nodes.Player.skeleton} />
        <skinnedMesh castShadow receiveShadow geometry={nodes.Shirt.geometry} material={materials.France} skeleton={nodes.Shirt.skeleton} />
        <skinnedMesh castShadow receiveShadow geometry={nodes.Shoes.geometry} material={materials['Kolo Boots']} skeleton={nodes.Shoes.skeleton} />
        <skinnedMesh castShadow receiveShadow geometry={nodes.Shorts.geometry} material={materials.France} skeleton={nodes.Shorts.skeleton} />
        <skinnedMesh castShadow receiveShadow geometry={nodes.Socks.geometry} material={materials.France} skeleton={nodes.Socks.skeleton} />
      </group>
      <group position={[-0.344, -0.436, 0.493]} rotation={[0, 1.551, 0]} scale={[0.27, 0.289, 0.27]}>
        <primitive object={nodes.Bone_1} />
        <skinnedMesh castShadow receiveShadow geometry={nodes.Gloves001.geometry} material={materials.Gloves} skeleton={nodes.Gloves001.skeleton} />
        <skinnedMesh castShadow receiveShadow geometry={nodes.Player001.geometry} material={materials.Dibu} skeleton={nodes.Player001.skeleton} />
        <skinnedMesh castShadow receiveShadow geometry={nodes.Shirt001.geometry} material={materials.Argentina} skeleton={nodes.Shirt001.skeleton} />
        <skinnedMesh castShadow receiveShadow geometry={nodes.Shoes001.geometry} material={materials.Boots} skeleton={nodes.Shoes001.skeleton} />
        <skinnedMesh castShadow receiveShadow geometry={nodes.Shorts001.geometry} material={materials.Argentina} skeleton={nodes.Shorts001.skeleton} />
        <skinnedMesh castShadow receiveShadow geometry={nodes.Socks001.geometry} material={materials.Argentina} skeleton={nodes.Socks001.skeleton} />
      </group>
      <group position={[0.001, 0.272, 0]} rotation={[-3.137, 0.113, -0.049]} scale={-0.009}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh033.geometry} material={materials['03 - Defaultdf']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh033_1.geometry} material={materials['03 - Defausdltdxc']} />
      </group>
      <group position={[11.62, 0, 2.46]} rotation={[-0.043, 1.458, 3.136]} scale={-0.009}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh590.geometry} material={nodes.Mesh590.material} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh590_1.geometry} material={materials.Bar} />
      </group>
      <mesh receiveShadow geometry={nodes.Pitch_Mark.geometry} material={nodes.Pitch_Mark.material} position={[11.62, 0, 2.46]} rotation={[-0.043, 1.458, 3.136]} scale={-0.009} />
      <mesh receiveShadow geometry={nodes.Net.geometry} material={materials.Net} position={[11.62, 0, 2.46]} rotation={[-0.043, 1.458, 3.136]} scale={-0.009} />
      <mesh receiveShadow geometry={nodes.Grass.geometry} material={materials.Grass} rotation={[0, -1.571, 0]} scale={67.718} />
    </group>
  )
}

useGLTF.preload('/3d/TheGreatestSaveOfAllTime.gltf')
